// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdyjerboyzoyxpzlkbdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkeWplcmJveXpveXhwemxrYmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjg3ODQsImV4cCI6MjA2ODk0NDc4NH0.fJe8BaiQlnnKY-uBXI4VIRnk4PTeDlScW2c8P68Xyt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});